---
title: "project3"
author: "Sean TSAI"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# House Prices Prediction

## Step 1: Data Importing/ Cleaning

```{r}
rawHouseDataTrain = read.csv("train.csv", stringsAsFactors = FALSE)
rawHouseDataTest = read.csv("test.csv", stringsAsFactors = FALSE)
summary(rawHouseDataTrain)
str(rawHouseDataTrain)

#We need to use characters for our Boruta screening of features
CharCategory = c(names(Filter(is.character, rawHouseDataTrain)), "MSSubClass")
intCategory = setdiff(names(rawHouseDataTrain[names(rawHouseDataTrain) != "Id" & names(rawHouseDataTrain) != "SalePrice" ]), CharCategory)

#Impute NAs by mean for int, 
for (i in intCategory){
  rawHouseDataTrain[,i] = ifelse(is.na(rawHouseDataTrain[,i]), mean(rawHouseDataTrain[,i],na.rm = TRUE), rawHouseDataTrain[,i] )
  rawHouseDataTest[,i] = ifelse(is.na(rawHouseDataTest[,i]), mean(rawHouseDataTest[,i],na.rm = TRUE), rawHouseDataTest[,i] )
  
}

#Impute NAs by "Missing" for factor
for(i in CharCategory){
  rawHouseDataTrain[,i] = ifelse(is.na(rawHouseDataTrain[,i]), "Missing", rawHouseDataTrain[,i])
  rawHouseDataTest[,i] = ifelse(is.na(rawHouseDataTest[,i]), "Missing", rawHouseDataTest[,i])
}


#Boruta Train package to identify important features (https://www.datacamp.com/community/tutorials/feature-selection-R-boruta)
library(Boruta)
set.seed(233)
borutaTrain <- Boruta(rawHouseDataTrain[names(rawHouseDataTrain) != "Id" & names(rawHouseDataTrain) != "SalePrice" ], rawHouseDataTrain$SalePrice ,  doTrace = 2)
print(borutaTrain)
plot(borutaTrain)

#Select only those features that passed the boruta screening
HouseDataTrainCleaned = rawHouseDataTrain[getSelectedAttributes(borutaTrain, withTentative = F)]
#Convert back characters into factors
HouseDataTrainCleaned[sapply(HouseDataTrainCleaned,is.character)] = lapply(HouseDataTrainCleaned[sapply(HouseDataTrainCleaned,is.character)], as.factor)

```

